version: '3.7'
services:
  redis:
    image: redis:latest
    container_name: cache
    restart: always
    ports:
      - '6379:6379'

  postgres:
    image: 'postgres:14-bullseye'
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qweQWE123
      - POSTGRES_DB=db
      - PGDATA=/var/lib/postgresql/data
      - LANG=en_US.utf8
    volumes:
      - './postgresql-data:/var/lib/postgresql/data'
    ports:
      - '5432:5432'